<? if( $showbanners ): ?>



<style>

#skladScreenGlideSmall

{

	display: none;

	position: absolute;

	left: 0px;

	top: 240px;

	width: 40px;

	height: 400px;

	z-index: 1000;

}

#skladScreenGlideBig 

{

	display: none;

	position: absolute;

	left: 0px;

	top: 240px;

	width: 600px;

	height: 400px;

	z-index: 1001;

}

</style>



<script language="JavaScript">

<!--

function skladSGShowHide(x)

{

   

    big   = document.getElementById('skladScreenGlideBig');

	small = document.getElementById('skladScreenGlideSmall');

	if(x == 'big')

	{ 

	

		big.style.display   = 'block';

		small.style.display = 'none';

	}

	else

	{

		big.style.display   = 'none'; 

		small.style.display = 'block';

	}

	return false;

}

//-->

</script>





<div id="skladScreenGlideSmall" onmouseover="return skladSGShowHide('big')">

	<script type='text/javascript'><!--//<![CDATA[

	   var m3_u = (location.protocol=='https:'?'https://ruscable.su/www/delivery/ajs.php':'http://ruscable.su/www/delivery/ajs.php');

	   var m3_r = Math.floor(Math.random()*99999999999);

	   if (!document.MAX_used) document.MAX_used = ',';

	   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);

	   document.write ("?zoneid=161");

	   document.write ('&amp;cb=' + m3_r);

	   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);

	   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));

	   document.write ("&amp;loc=" + escape(window.location));

	   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));

	   if (document.context) document.write ("&context=" + escape(document.context));

	   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");

	   document.write ("'><\/scr"+"ipt>");

	//]]>--></script><noscript><a href='http://ruscable.su/www/delivery/ck.php?n=ab00d97e&amp;cb=23567272472457' target='_blank'><img src='http://ruscable.su/www/delivery/avw.php?zoneid=161&amp;cb=23567272472457&amp;n=ab00d97e' border='0' alt='' /></a></noscript>

</div>



<div id="skladScreenGlideBig" onmouseout="return skladSGShowHide('small')">

	<script type='text/javascript'><!--//<![CDATA[

	   var m3_u = (location.protocol=='https:'?'https://ruscable.su/www/delivery/ajs.php':'http://ruscable.su/www/delivery/ajs.php');

	   var m3_r = Math.floor(Math.random()*99999999999);

	   if (!document.MAX_used) document.MAX_used = ',';

	   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);

	   document.write ("?zoneid=162");

	   document.write ('&amp;cb=' + m3_r);

	   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);

	   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));

	   document.write ("&amp;loc=" + escape(window.location));

	   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));

	   if (document.context) document.write ("&context=" + escape(document.context));

	   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");

	   document.write ("'><\/scr"+"ipt>");

	//]]>--></script><noscript><a href='http://ruscable.su/www/delivery/ck.php?n=ab00d97e&amp;cb=478356835684568' target='_blank'><img src='http://ruscable.su/www/delivery/avw.php?zoneid=162&amp;cb=478356835684568&amp;n=ab00d97e' border='0' alt='' /></a></noscript>

</div>



<? endif; ?>

