
<?
if($showbanners){
    $zid=121;
    ?>
    <div id="finishline" style="text-align: center; height: 300px;">
        <iframe id='af8de12d' name='af8de12d' src='//ruscable.su/www/delivery/afr.php?zoneid=<?=$zid?>&amp;cb=698743549689685465' frameborder='0' scrolling='no' width='100%' height='300'></iframe>

    </div>
<?}?>
<footer class="row">
    <div class="container">

        <div class="col-md-7">
 <p>
                © «РусКабель», 1999-<?=date('Y'); ?><br><br>
                Все права защищены и охраняются законом. Администрация RusCable.Ru
                не несет ответственности за высказывания третьих лиц. Мнение редакции может не совпадать с мнением авторов материалов. 18+
                Перепечатка информации возможна только при соблюдении <a href="//www.ruscable.ru/conditions.html">следующих условий</a>.
            </p>
        </div>
        <div class="col-md-5">
            <p>
                111123, Москва, Электродный проезд, д.8А, оф.18<br />
                Телефон: Телефон: <a href="tel:74952293336">+7 495 229 33 36 (мнк)</a> <br>
                Viber/WhatsApp/Telegram: <a href="tel:79990033336">+7 999 003 33 36</a>
                <br>
                E-mail: <a href="mailto:mail@ruscable.ru">mail@ruscable.ru</a>
                <!-- <a href="//www.2293336.ru/about/contact.html">Контактная информация медиахолдинга РусКабель</a><br /> -->
                <br />
                <br />
            </p>
        </div>
        <noindex>
            <ul id="schrtchiki"  style="margin-bottom: 0;">
                <li>

                    <!-- Top100 (Kraken) Widget -->
                    <span id="top100_widget"></span>
                    <!-- END Top100 (Kraken) Widget -->

                    <!-- Top100 (Kraken) Counter -->
                    <script>
                        (function (w, d, c) {
                        (w[c] = w[c] || []).push(function() {
                            var options = {
                                project: 794677,
                                element: 'top100_widget',
                            };
                            try {
                                w.top100Counter = new top100(options);
                            } catch(e) { }
                        });
                        var n = d.getElementsByTagName("script")[0],
                        s = d.createElement("script"),
                        f = function () { n.parentNode.insertBefore(s, n); };
                        s.type = "text/javascript";
                        s.async = true;
                        s.src =
                        (d.location.protocol == "https:" ? "https:" : "http:") +
                        "//st.top100.ru/top100/top100.js";

                        if (w.opera == "[object Opera]") {
                        d.addEventListener("DOMContentLoaded", f, false);
                    } else { f(); }
                    })(window, document, "_top100q");
                    </script>
                    <noscript>
                      <img src="//counter.rambler.ru/top100.cnt?pid=794677" alt="??100" />
                    </noscript>
                    <!-- END Top100 (Kraken) Counter -->

                </li>


                <li>
                    <!-- Rating@Mail.ru counter -->
                      <script type="text/javascript">
                      var _tmr = window._tmr || (window._tmr = []);
                      _tmr.push({id: "973713", type: "pageView", start: (new Date()).getTime()});
                      (function (d, w, id) {
                        if (d.getElementById(id)) return;
                        var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
                        ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
                        var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
                        if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
                      })(document, window, "topmailru-code");
                      </script><noscript><div>
                      <img src="//top-fwz1.mail.ru/counter?id=973713;js=na" style="border:0;position:absolute;left:-9999px;" alt="" />
                      </div></noscript>
                      <!-- //Rating@Mail.ru counter -->
                        <!-- Rating@Mail.ru logo -->
                      <a href="https://top.mail.ru/jump?from=973713">
                      <img src="//top-fwz1.mail.ru/counter?id=973713;t=373;l=1"
                      style="border:0;" height="18" width="88" alt="????Mail.ru" /></a>
                      <!-- //Rating@Mail.ru logo -->

                </li>
                <li>
                    <!-- ??????? -->
                    <script language="javascript">
                        java="1.0";
                        java1=""+"&refer="+escape(document.referrer)+"&page="+
                            escape(window.location.href);
                        document.cookie="astratop=1; path=/"; java1+="&c="+(document.cookie?"yes":"now");
                    </script>
                    <script language="javascript1.1">java="1.1";java1+="&java="+(navigator.javaEnabled()?"yes":"now")</script>
                    <script language="javascript1.2">java="1.2";
                        java1+="&razresh="+screen.width+'x'+screen.height+"&cvet="+
                            (((navigator.appName.substring(0,3)=="Mic"))?
                                screen.colorDepth:screen.pixelDepth)</script><script language="javascript1.3">java="1.3"</script>
                    <script language="javascript">java1+="&jscript="+java+"&rand="+Math.random();
                        document.write("<a href='//top.ruscable.ru/in.php?id=1' target='_blank'><img "+
                            " src='//top.ruscable.ru/img.php?id=1&"+java1+"&' border=0  width=88 height=31 alt='???????'></a>")</script>
                    <noscript><a href="//www.ruscable.ru/" target=_blank><img src="//top.ruscable.ru/img.php?id=1" border=0 width=88 height=31 alt="???????"></a></noscript>
                    <!-- /??????? -->
                </li>

            </ul>
        </noindex>
    </div>
</footer>
</div>

<div class="md-modal md-effect-1" id="showlist">
    <div class="md-content">
        <div class="md-close"></div>
        <div class="head">
            Мой список
        </div>
        <div class="contentList">

        </div>
    </div>
</div>

<div class="md-overlay"></div>



<script src="/misc/new/bootstrap.min.js"></script>
<script src="/misc/new/jquery.jcarousel.min.js"></script>
<script src="/misc/new/lightbox.min.js"></script>
<script src="/misc/new/waypoints.min.js"></script>
<script src="/misc/new/classie.js"></script>
<script src="/misc/new/livesearch.js"></script>
<script src="/misc/new/modalEffects.js"></script>
<script src="/misc/new/jquery.formstyler.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {

        $("#search").submit(function( e ) {
            e.preventDefault();
            var q = $("#search input").val();
            window.location.href = "/"+q;
        });

        $('select').styler();

        $('.city-select1 select').bind('change', function () {
            var url = $(this).val();
            if (url) {
                window.location = url;
            }
            return false;
        });
    });
</script>

<!-- BEGIN JIVOSITE CODE {literal} -->
<!-- <script type='text/javascript'>
(function(){ var widget_id = 'QfRUnke74N';var d=document;var w=window;function l(){
var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script> -->
<!-- {/literal} END JIVOSITE CODE -->
<script>
        (function(w,d,u){
                var s=d.createElement('script');s.async=true;s.src=u+'?'+(Date.now()/60000|0);
                var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
        })(window,document,'https://cdn.bitrix24.ru/b9393327/crm/site_button/loader_1_2uhwjq.js');
</script>

<?
$end_time = microtime();
$end_array = explode(" ",$end_time);
$end_time = $end_array[1] + $end_array[0];
$time = $end_time - $start_time;

if($_SESSION['login']=="vladimir"){printf("<center>генерация %f сек</center>",$time);
}
?>
</body>
</html>


